/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.pms;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.ServerSocket;
import java.net.Socket;

public class ServerApp {

  public static void main(String[] args) {
    try (ServerSocket ss = new ServerSocket(8888)) {
      System.out.println("클라이언트 기다리는 ");

      try (Socket socket = ss.accept();
          BufferedReader in = new BufferedReader(new InputStreamReader(((socket.getInputStream()))));
          PrintStream out = new PrintStream(socket.getOutputStream())){



        System.out.println(in.readLine());
        out.println("나도 반갑다.");


      } catch (Exception e) {
        e.printStackTrace();
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
