/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.pms;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.Socket;

public class ClientApp {

  public static void main(String[] args) {
    try(Socket socket = new Socket("localhost", 8888);
        BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
        PrintStream out = new PrintStream(socket.getOutputStream())) {

      //서버에 인삿말 보냄.
      //서버가 응답한 메세지 출력
      out.println("안녕");
      out.flush();
      System.out.println(in.readLine());

    } catch (Exception e) {

    }
  }
}
