/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.pms;

import java.util.Scanner;
import java.sql.Date;


public class App {
    public static void main(String[] args) {
        
       Point[] p = new Point[5];
       for(int i = 0; i < p.length; i++) { 
           p[i] = new Point();
           p[i].prn();
       }
       

    }

    class Point{
        int x,y;

        void prn() {
            System.out.println("(" + x + "," +y + ")");
        }
    }
    
}



 